name: mentali
description: "Playground"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  get_it: ^8.0.3
  intl: ^0.20.1
  floor: ^1.5.0
  retrofit: ^4.4.2
  logger: ^2.4.0  # for logging purpose
  json_annotation: ^4.9.0
  flutter_hooks: ^0.20.5
  cached_network_image: ^3.4.1
  dio: ^5.7.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  http: ^1.3.0
  flutter_bloc: ^9.0.0
  shimmer: ^3.0.0
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3
  connectivity_plus: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: '>=8.0.0 <10.0.0'
  build_runner: ^2.4.14
  json_serializable: ^6.8.0
  floor_generator: ^1.5.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700